import Head from 'next/head'
import Image from 'next/image'
import { useSession, signIn, signOut } from "next-auth/react"
import { useRouter } from 'next/router'



export default function Home() {
  const router = useRouter()

  const { data: session } = useSession()


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-4xl mb-4">this is main page</h1>
        {session ?
          <>
            <h1>User already login</h1>
          </>
          :
          <>
            <h1>Please sign in first</h1>
            <button
            // onClick={()=>{
            //   router.push("/signin")
            // }}
            onClick={()=>signIn()}
              type="button"
              className="my-5 bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-md shadow-md transition-colors duration-300"
            >
              Sign In
            </button>

          </>
        }
      </main>
    </>
  )
}

