// import Head from 'next/head'
// import Image from 'next/image'

// import { useSession, signIn, signOut } from "next-auth/react"

// import { FaGoogle, FaDiscord, FaGithub } from 'react-icons/fa';



// export default function SignIn() {
//     const { data: session } = useSession()

//     return (
//         <>
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <main>
//                 {session ?
//                     <h1>Login is succefully</h1>
//                     :
//                     <>
//                     <SocialSignInButtons />
//                     </>
//                 }
//             </main>
//         </>
//     )
// }

// const SocialSignInButtons = () => {
//     return (
//       <div className="flex flex-col items-center mt-8">
//         <button onClick={()=>signIn("google")} className="bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 rounded-md shadow-md transition-colors duration-300 mb-4 flex items-center">
//           <FaGoogle className="mr-2" />
//           Sign in with Google
//         </button>
//         <button onClick={()=>signIn("discord")} className="bg-purple-500 hover:bg-purple-600 text-white font-semibold py-2 px-4 rounded-md shadow-md transition-colors duration-300 mb-4 flex items-center">
//           <FaDiscord className="mr-2" />
//           Sign in with Discord
//         </button>
//         <button onClick={()=>signIn("github")} className="bg-gray-800 hover:bg-gray-900 text-white font-semibold py-2 px-4 rounded-md shadow-md transition-colors duration-300 flex items-center">
//           <FaGithub className="mr-2" />
//           Sign in with GitHub
//         </button>
//       </div>
//     );
//   };




  import type { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import { getProviders, signIn } from "next-auth/react"
import { getServerSession } from "next-auth/next"
import { authOptions } from "./api/auth/[...nextauth]";

export default function SignIn({ providers }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      {Object.values(providers).map((provider) => (
        <div key={provider.name}>
          <button onClick={() => signIn(provider.id)}>
            Sign in with {provider.name}
          </button>
        </div>
      ))}
    </>
  )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerSession(context.req, context.res, authOptions);
  
  // If the user is already logged in, redirect.
  // Note: Make sure not to redirect to the same page
  // To avoid an infinite loop!
  if (session) {
    return { redirect: { destination: "/" } };
  }

  const providers = await getProviders();
  
  return {
    props: { providers: providers ?? [] },
  }
}