import Head from 'next/head'
import Image from 'next/image'

import { useSession, signIn, signOut } from "next-auth/react"



export default function SignIn() {
    const { data: session } = useSession()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {session ?
                    <h1>Login is succefully</h1>
                    :
                    <>
                        <h1>Sign In</h1>
                        Not signed in <br />
                        <button onClick={() => signIn()}>Sign in</button>
                    </>
                }
            </main>
        </>
    )
}
